name: Build Infra and Deploy Application

on:
  push:
    branches:  main 
    paths-ignore: 
      - readme.md

env:
  tf_version: '1.7.3'
  tg_version: '0.55.1'

jobs:
  infra:
    runs-on: ubuntu-latest
    outputs:
      bucket: ${{ steps.tg_bucket_name.outputs.tg_action_output }}
      url:    ${{ steps.tg_cf_url.outputs.tg_action_output }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Terragrunt Apply
        uses: gruntwork-io/terragrunt-action@v2
        id: tg_apply
        with: 
          tf_version:  ${{ env.tf_version }}
          tg_version:  ${{ env.tg_version }} 
          tg_dir: infrastructure
          tg_command: 'run-all apply'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Terragrunt Get Bucket Name
        uses: gruntwork-io/terragrunt-action@v2
        id: tg_bucket_name
        with: 
          tf_version:  ${{ env.tf_version }}
          tg_version:  ${{ env.tg_version }} 
          tg_dir: infrastructure/config/us-east-1/s3bucket/
          tg_command: '--terragrunt-log-level error  output -raw bucket_id'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_LOG: error

      - name: Terragrunt Get Cloudfront URL
        uses: gruntwork-io/terragrunt-action@v2
        id: tg_cf_url
        with: 
          tf_version:  ${{ env.tf_version }}
          tg_version:  ${{ env.tg_version }} 
          tg_dir: infrastructure/config/us-east-1/cloudfront/
          tg_command: '--terragrunt-log-level error  output -raw aws_cloudfront_distribution_domain_name'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_LOG: error

      
  app:
    needs: infra
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  
      - name: Install Python Dependencies
        run: |
          pip install -r  app/required-py-packages.txt  
      - name: Deploy Application
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET: ${{ needs.infra.outputs.bucket }}
          CF_URL: "https://${{ needs.infra.outputs.url }}"
        run: |
          python app/main.py  
